language: node_js
node_js:
  - '5'
before_install:
  - npm install -g npm@3
  - npm --version
addons:
  sauce_connect:
    username: andyearnshaw
    access_key:
      secure: 'OslPEaqVgNH+9YWwtEIJE4/Ot+RmSonIYMxvxMjnaaLAkoYX34nJzaB8vPFP1txDwkDHpOy+MiQ8hKYhyilw5Ydr11O2IEuhVjcJThKSoN3yMTe6FHpXQKO9uC1loaRwJs2uV0go+P4ooywZ8Y72/RtKXk0OOhn5Lg5ekb3wMRg='

cache:
  directories:
    - node_modules

sudo: false
